import { describe, expect, it } from "vitest";
import { resolveConfig } from "../config.js";
import type { MaterialSymbolsConfig } from "../types.js";

const minimalConfig: MaterialSymbolsConfig = {
  icons: ["home"],
};

describe("resolveConfig", () => {
  it("applies all defaults for minimal config", () => {
    const resolved = resolveConfig(minimalConfig);

    expect(resolved.icons).toEqual(["home"]);
    expect(resolved.outputDir).toBe("src/icons");
    expect(resolved.style).toBe("outlined");
    expect(resolved.format).toBe("mui");
    expect(resolved.optimize).toBe(true);
    expect(resolved.useClientDirective).toBe(true);
    expect(resolved.barrel).toBe(true);
    expect(resolved.extension).toBe("tsx");
    expect(resolved.declarations).toBe(false);
    expect(resolved.concurrency).toBe(25);
    expect(resolved.header).toBe("Auto-generated by material-symbols-cli. Do not edit.");
  });

  it("uses default variant when none provided", () => {
    const resolved = resolveConfig(minimalConfig);
    expect(resolved.variants).toEqual([{ fill: 0, weight: 400, grade: 0, opticalSize: 24 }]);
  });

  it("uses provided variants when present", () => {
    const variants = [{ fill: 1 as const, weight: 700 as const }];
    const resolved = resolveConfig({ ...minimalConfig, variants });
    expect(resolved.variants).toEqual(variants);
  });

  it("falls back to default variant when variants array is empty", () => {
    const resolved = resolveConfig({ ...minimalConfig, variants: [] });
    expect(resolved.variants).toEqual([{ fill: 0, weight: 400, grade: 0, opticalSize: 24 }]);
  });

  it("resolves naming defaults", () => {
    const resolved = resolveConfig(minimalConfig);
    expect(resolved.naming).toEqual({
      convention: "PascalCase",
      prefix: "",
      suffix: "",
      overrides: {},
    });
  });

  it("resolves naming overrides", () => {
    const resolved = resolveConfig({
      ...minimalConfig,
      naming: { prefix: "Icon", overrides: { home: "House" } },
    });
    expect(resolved.naming.prefix).toBe("Icon");
    expect(resolved.naming.convention).toBe("PascalCase");
    expect(resolved.naming.overrides).toEqual({ home: "House" });
  });

  it("resolves defaultProps with defaults", () => {
    const resolved = resolveConfig(minimalConfig);
    expect(resolved.defaultProps).toEqual({
      size: 24,
      color: "currentColor",
      className: "",
    });
  });

  it("applies custom defaultProps", () => {
    const resolved = resolveConfig({
      ...minimalConfig,
      defaultProps: { size: 48, color: "#000" },
    });
    expect(resolved.defaultProps.size).toBe(48);
    expect(resolved.defaultProps.color).toBe("#000");
    expect(resolved.defaultProps.className).toBe("");
  });

  it("disables header when set to false", () => {
    const resolved = resolveConfig({ ...minimalConfig, header: false });
    expect(resolved.header).toBe(false);
  });

  it("uses custom header string", () => {
    const resolved = resolveConfig({
      ...minimalConfig,
      header: "Custom header",
    });
    expect(resolved.header).toBe("Custom header");
  });

  it("resolves extension based on format", () => {
    const cases: [string, string][] = [
      ["mui", "tsx"],
      ["react", "tsx"],
      ["react-native", "tsx"],
      ["solid", "tsx"],
      ["preact", "tsx"],
      ["qwik", "tsx"],
      ["vue", "vue"],
      ["angular", "ts"],
      ["svelte", "svelte"],
      ["lit", "ts"],
      ["web-component", "ts"],
      ["flutter", "dart"],
      ["svg", "svg"],
    ];

    for (const [format, expectedExt] of cases) {
      const resolved = resolveConfig({
        ...minimalConfig,
        format: format as MaterialSymbolsConfig["format"],
      });
      expect(resolved.extension).toBe(expectedExt);
    }
  });

  it("allows custom extension override", () => {
    const resolved = resolveConfig({
      ...minimalConfig,
      format: "react",
      extension: "jsx",
    });
    expect(resolved.extension).toBe("jsx");
  });

  it("handles 'all' icons config", () => {
    const resolved = resolveConfig({ icons: "all" });
    expect(resolved.icons).toBe("all");
  });
});
