import { describe, expect, it } from "vitest";
import { getGenerator } from "../generators/index.js";
import { generateBarrel } from "../generators/barrel.js";
import { toKebab } from "../generators/shared.js";
import type { OutputFormat, Config } from "../types.js";

const makeConfig = (overrides: Partial<Config> = {}): Config => ({
  icons: ["home"],
  outputDir: "src/icons",
  style: "outlined",
  format: "mui",
  variants: [{ fill: 0, weight: 400, grade: 0, opticalSize: 24 }],
  naming: {
    convention: "PascalCase",
    prefix: "",
    suffix: "",
    overrides: {},
  },
  defaultProps: { size: 24, color: "currentColor", className: "" },
  optimize: true,
  useClientDirective: true,
  barrel: true,
  extension: "tsx",
  declarations: false,
  concurrency: 25,
  header: "Auto-generated by material-symbols-cli. Do not edit.",
  ...overrides,
});

const SAMPLE_PATH = '<path d="M240-200h120v-240h240"/>';
const COMPONENT = "HomeIcon";

describe("toKebab", () => {
  it("converts PascalCase to kebab-case", () => {
    expect(toKebab("HomeIcon")).toBe("home-icon");
  });

  it("handles all-lowercase when no lowercase-to-uppercase transition", () => {
    expect(toKebab("SVGIcon")).toBe("svgicon");
  });

  it("handles single word", () => {
    expect(toKebab("Home")).toBe("home");
  });
});

describe("getGenerator", () => {
  const allFormats: OutputFormat[] = [
    "mui",
    "react",
    "react-native",
    "vue",
    "angular",
    "svelte",
    "solid",
    "preact",
    "qwik",
    "lit",
    "web-component",
    "flutter",
    "svg",
  ];

  for (const format of allFormats) {
    it(`returns a generator function for ${format}`, () => {
      const gen = getGenerator(format);
      expect(typeof gen).toBe("function");
    });
  }
});

describe("mui generator", () => {
  const generate = getGenerator("mui");

  it("generates a createSymbolIcon call", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, makeConfig());
    expect(output).toContain("createSymbolIcon");
    expect(output).toContain(`"${COMPONENT}"`);
    expect(output).toContain("export default createSymbolIcon(");
  });

  it("includes the 'use client' directive", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, makeConfig());
    expect(output).toContain('"use client"');
  });

  it("omits 'use client' when disabled", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, makeConfig({ useClientDirective: false }));
    expect(output).not.toContain('"use client"');
  });

  it("includes header comment", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, makeConfig());
    expect(output).toContain("// Auto-generated");
  });

  it("omits header when disabled", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, makeConfig({ header: false }));
    expect(output).not.toContain("// Auto-generated");
  });

  it("optimizes single-path SVGs to extract d attribute", () => {
    const singlePath = '<path d="M10 20v-6h4v6h5V10h3L12 3 2 10h3v10z"/>';
    const output = generate(COMPONENT, singlePath, makeConfig());
    expect(output).toContain('d="M10 20v-6h4v6h5V10h3L12 3 2 10h3v10z"');
    expect(output).not.toContain("<>");
  });

  it("wraps multi-path SVGs in Fragment", () => {
    const multiPath = '<path d="M10 20"/><path d="M5 5"/>';
    const output = generate(COMPONENT, multiPath, makeConfig());
    expect(output).toContain("<>");
    expect(output).toContain("</>");
  });

  it("imports createSymbolIcon from utils", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, makeConfig());
    expect(output).toContain('import createSymbolIcon from "./utils/createSymbolIcon"');
  });
});

describe("react generator", () => {
  const generate = getGenerator("react");

  it("generates a function component with SVGProps", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, makeConfig());
    expect(output).toContain("SVGProps");
    expect(output).toContain(`function ${COMPONENT}`);
    expect(output).toContain("xmlns");
  });

  it("uses configured default props", () => {
    const output = generate(
      COMPONENT,
      SAMPLE_PATH,
      makeConfig({ defaultProps: { size: 48, color: "#000", className: "" } }),
    );
    expect(output).toContain("size = 48");
    expect(output).toContain('color = "#000"');
  });

  it("includes className handling when configured", () => {
    const output = generate(
      COMPONENT,
      SAMPLE_PATH,
      makeConfig({ defaultProps: { size: 24, color: "currentColor", className: "icon" } }),
    );
    expect(output).toContain("icon");
  });
});

describe("vue generator", () => {
  const generate = getGenerator("vue");
  const config = makeConfig({ format: "vue", extension: "vue" });

  it("generates a Vue SFC with template and script setup", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, config);
    expect(output).toContain("<template>");
    expect(output).toContain("</template>");
    expect(output).toContain('<script setup lang="ts">');
    expect(output).toContain("defineProps");
    expect(output).toContain("withDefaults");
  });

  it("uses HTML comment for header", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, config);
    expect(output).toContain("<!-- Auto-generated");
  });

  it("sets defineOptions name", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, config);
    expect(output).toContain(`name: "${COMPONENT}"`);
  });
});

describe("angular generator", () => {
  const generate = getGenerator("angular");
  const config = makeConfig({ format: "angular", extension: "ts" });

  it("generates a standalone Angular component", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, config);
    expect(output).toContain("@Component");
    expect(output).toContain("standalone: true");
    expect(output).toContain(`export class ${COMPONENT}Component`);
  });

  it("generates correct kebab-case selector", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, config);
    expect(output).toContain('selector: "home-icon"');
  });
});

describe("svelte generator", () => {
  const generate = getGenerator("svelte");
  const config = makeConfig({ format: "svelte", extension: "svelte" });

  it("generates a Svelte 5 component with $props()", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, config);
    expect(output).toContain("$props()");
    expect(output).toContain('<script lang="ts">');
    expect(output).toContain("<svg");
  });

  it("uses HTML comment for header", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, config);
    expect(output).toContain("<!-- Auto-generated");
  });
});

describe("solid generator", () => {
  const generate = getGenerator("solid");

  it("generates a SolidJS component", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, makeConfig());
    expect(output).toContain("solid-js");
    expect(output).toContain(`function ${COMPONENT}`);
    expect(output).toContain("SvgSVGAttributes");
  });

  it("includes 'use client' directive", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, makeConfig());
    expect(output).toContain('"use client"');
  });
});

describe("preact generator", () => {
  const generate = getGenerator("preact");

  it("generates a Preact component", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, makeConfig());
    expect(output).toContain('from "preact"');
    expect(output).toContain(`function ${COMPONENT}`);
    expect(output).toContain("SVGAttributes");
  });
});

describe("qwik generator", () => {
  const generate = getGenerator("qwik");
  const config = makeConfig({ format: "qwik" });

  it("generates a Qwik component with component$", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, config);
    expect(output).toContain("component$");
    expect(output).toContain(`export const ${COMPONENT}`);
    expect(output).toContain("@builder.io/qwik");
  });

  it("does not import unused QwikIntrinsicElements", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, config);
    expect(output).not.toContain("QwikIntrinsicElements");
  });
});

describe("lit generator", () => {
  const generate = getGenerator("lit");
  const config = makeConfig({ format: "lit", extension: "ts" });

  it("generates a LitElement with decorators", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, config);
    expect(output).toContain("LitElement");
    expect(output).toContain("@customElement");
    expect(output).toContain("@property");
    expect(output).toContain(`class ${COMPONENT}`);
  });

  it("sets correct custom element tag name", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, config);
    expect(output).toContain('"home-icon"');
  });

  it("registers in HTMLElementTagNameMap", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, config);
    expect(output).toContain("HTMLElementTagNameMap");
  });
});

describe("web-component generator", () => {
  const generate = getGenerator("web-component");
  const config = makeConfig({ format: "web-component", extension: "ts" });

  it("generates a Custom Element with Shadow DOM", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, config);
    expect(output).toContain("HTMLElement");
    expect(output).toContain("attachShadow");
    expect(output).toContain("customElements.define");
  });

  it("handles observed attributes for size and color", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, config);
    expect(output).toContain('observedAttributes = ["size", "color"]');
    expect(output).toContain("attributeChangedCallback");
  });
});

describe("svg generator", () => {
  const generate = getGenerator("svg");
  const config = makeConfig({ format: "svg", extension: "svg" });

  it("generates a valid SVG file", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, config);
    expect(output).toContain("<svg");
    expect(output).toContain("xmlns");
    expect(output).toContain("</svg>");
    expect(output).toContain(SAMPLE_PATH);
  });

  it("sets configured size and color", () => {
    const output = generate(
      COMPONENT,
      SAMPLE_PATH,
      makeConfig({
        format: "svg",
        defaultProps: { size: 48, color: "#fff", className: "" },
      }),
    );
    expect(output).toContain('width="48"');
    expect(output).toContain('height="48"');
    expect(output).toContain('fill="#fff"');
  });

  it("uses HTML comment for header", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, config);
    expect(output).toContain("<!-- Auto-generated");
  });
});

describe("generateBarrel", () => {
  const icons = [
    { componentName: "Home", fileName: "Home" },
    { componentName: "Search", fileName: "Search" },
    { componentName: "ArrowBack", fileName: "ArrowBack" },
  ];

  it("generates default re-exports for mui", () => {
    const config = makeConfig({ extension: "tsx" });
    const output = generateBarrel(icons, config);
    expect(output).toContain('export { default as Home } from "./Home"');
    expect(output).toContain('export { default as Search } from "./Search"');
    expect(output).not.toContain("./Home.");
  });

  it("generates named exports for angular", () => {
    const config = makeConfig({ format: "angular", extension: "ts" });
    const output = generateBarrel(icons, config);
    expect(output).toContain('export { Home } from "./Home"');
    expect(output).not.toContain("default as");
  });

  it("preserves .vue extension in imports", () => {
    const config = makeConfig({ format: "vue", extension: "vue" });
    const output = generateBarrel(icons, config);
    expect(output).toContain('from "./Home.vue"');
  });

  it("preserves .svelte extension in imports", () => {
    const config = makeConfig({ format: "svelte", extension: "svelte" });
    const output = generateBarrel(icons, config);
    expect(output).toContain('from "./Home.svelte"');
  });

  it("preserves .svg extension for SVG format", () => {
    const config = makeConfig({ format: "svg", extension: "svg" });
    const output = generateBarrel(icons, config);
    expect(output).toContain('from "./Home.svg"');
  });

  it("uses named exports for qwik", () => {
    const config = makeConfig({ format: "qwik", extension: "tsx" });
    const output = generateBarrel(icons, config);
    expect(output).toContain("export { Home }");
    expect(output).not.toContain("default as");
  });

  it("uses named exports for lit", () => {
    const config = makeConfig({ format: "lit", extension: "ts" });
    const output = generateBarrel(icons, config);
    expect(output).toContain("export { Home }");
  });

  it("uses named exports for web-component", () => {
    const config = makeConfig({ format: "web-component", extension: "ts" });
    const output = generateBarrel(icons, config);
    expect(output).toContain("export { Home }");
  });

  it("includes header comment when configured", () => {
    const config = makeConfig();
    const output = generateBarrel(icons, config);
    expect(output).toContain("// Auto-generated");
  });

  it("omits header when disabled", () => {
    const config = makeConfig({ header: false });
    const output = generateBarrel(icons, config);
    expect(output).not.toContain("//");
  });
});

describe("flutter generator", () => {
  const generate = getGenerator("flutter");
  const config = makeConfig({ format: "flutter", extension: "dart" });

  it("generates a StatelessWidget class", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, config);
    expect(output).toContain(`class ${COMPONENT} extends StatelessWidget`);
    expect(output).toContain("Widget build(BuildContext context)");
  });

  it("uses SvgPicture.string for rendering", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, config);
    expect(output).toContain("SvgPicture.string(");
    expect(output).toContain("flutter_svg");
    expect(output).toContain("ColorFilter.mode(color, BlendMode.srcIn)");
  });

  it("sets default size and color from config", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, config);
    expect(output).toContain("this.size = 24");
    expect(output).toContain("Color(0xFF000000)");
  });

  it("converts hex color correctly", () => {
    const customConfig = makeConfig({
      format: "flutter",
      extension: "dart",
      defaultProps: { size: 32, color: "#ff5722", className: "" },
    });
    const output = generate(COMPONENT, SAMPLE_PATH, customConfig);
    expect(output).toContain("this.size = 32");
    expect(output).toContain("Color(0xFFff5722)");
  });

  it("extracts path d attribute from SVG path element", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, config);
    expect(output).toContain("M240-200h120v-240h240");
  });

  it("includes header comment", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, config);
    expect(output).toContain("// Auto-generated");
  });

  it("omits header when disabled", () => {
    const output = generate(
      COMPONENT,
      SAMPLE_PATH,
      makeConfig({ format: "flutter", extension: "dart", header: false }),
    );
    expect(output).not.toContain("// Auto-generated");
  });
});

describe("react-native generator", () => {
  const generate = getGenerator("react-native");

  it("generates a component using react-native-svg", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, makeConfig());
    expect(output).toContain('from "react-native-svg"');
    expect(output).toContain("Svg");
    expect(output).toContain("Path");
    expect(output).toContain(`const ${COMPONENT}`);
  });

  it("exports as default", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, makeConfig());
    expect(output).toContain(`export default ${COMPONENT}`);
  });

  it("defines a Props interface extending SvgProps", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, makeConfig());
    expect(output).toContain(`interface ${COMPONENT}Props extends SvgProps`);
    expect(output).toContain("size?: number");
  });

  it("uses configured default props", () => {
    const output = generate(
      COMPONENT,
      SAMPLE_PATH,
      makeConfig({ defaultProps: { size: 48, color: "#000", className: "" } }),
    );
    expect(output).toContain("size = 48");
    expect(output).toContain('color = "#000"');
  });

  it("extracts path d attributes into Path elements", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, makeConfig());
    expect(output).toContain('<Path d="M240-200h120v-240h240"');
  });

  it("handles multi-path SVGs", () => {
    const multiPath = '<path d="M10 20"/><path d="M5 5"/>';
    const output = generate(COMPONENT, multiPath, makeConfig());
    expect(output).toContain('<Path d="M10 20"');
    expect(output).toContain('<Path d="M5 5"');
  });

  it("includes header comment", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, makeConfig());
    expect(output).toContain("// Auto-generated");
  });

  it("omits header when disabled", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, makeConfig({ header: false }));
    expect(output).not.toContain("// Auto-generated");
  });

  it("spreads rest props onto Svg", () => {
    const output = generate(COMPONENT, SAMPLE_PATH, makeConfig());
    expect(output).toContain("{...props}");
  });
});
