import { existsSync } from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import type {
  ConfigModule,
  MaterialSymbolsConfig,
  OutputFormat,
  Config,
  Defaults,
  Naming,
  SymbolVariant,
} from "./types.js";

const DEFAULT_VARIANT: SymbolVariant = {
  fill: 0,
  weight: 400,
  grade: 0,
  opticalSize: 24,
};

const extensionForFormat = (format: OutputFormat) => {
  switch (format) {
    case "mui":
    case "react":
    case "react-native":
    case "solid":
    case "preact":
    case "qwik":
      return "tsx";
    case "vue":
      return "vue";
    case "angular":
      return "ts";
    case "svelte":
      return "svelte";
    case "lit":
    case "web-component":
      return "ts";
    case "flutter":
      return "dart";
    case "svg":
      return "svg";
  }
};

const NAMING_DEFAULTS: Naming = {
  convention: "PascalCase",
  prefix: "",
  suffix: "",
  overrides: {},
};

const PROP_DEFAULTS: Defaults = {
  size: 24,
  color: "currentColor",
  className: "",
};

export const resolveConfig = (userConfig: MaterialSymbolsConfig) => {
  const format = userConfig.format ?? "mui";
  return {
    icons: userConfig.icons,
    outputDir: userConfig.outputDir ?? "src/icons",
    style: userConfig.style ?? "outlined",
    format,
    variants: userConfig.variants && userConfig.variants.length > 0 ? userConfig.variants : [DEFAULT_VARIANT],
    naming: { ...NAMING_DEFAULTS, ...userConfig.naming },
    defaultProps: { ...PROP_DEFAULTS, ...userConfig.defaultProps },
    optimize: userConfig.optimize ?? true,
    useClientDirective: userConfig.useClientDirective ?? true,
    barrel: userConfig.barrel ?? true,
    extension: userConfig.extension ?? extensionForFormat(format),
    declarations: userConfig.declarations ?? false,
    concurrency: userConfig.concurrency ?? 25,
    header:
      userConfig.header === false
        ? false
        : typeof userConfig.header === "string"
          ? userConfig.header
          : "Auto-generated by material-symbols-cli. Do not edit.",
  } satisfies Config;
};

export const defineConfig = (config: MaterialSymbolsConfig) => config;

const CONFIG_FILES = [
  "material-symbols.config.mts",
  "material-symbols.config.ts",
  "material-symbols.config.mjs",
  "material-symbols.config.js",
] as const;

export const loadConfigFile = async (cwd: string) => {
  for (const fileName of CONFIG_FILES) {
    const filePath = path.resolve(cwd, fileName);
    if (existsSync(filePath)) {
      const fileUrl = pathToFileURL(filePath).href;
      const configModule = (await import(fileUrl)) as ConfigModule;
      if (!configModule.default) {
        throw new Error(
          `Config file "${fileName}" must have a default export.\n` +
            `Example:\n  import { defineConfig } from "@hianali/material-symbols-cli/config";\n` +
            `  export default defineConfig({ icons: ["home"] });`,
        );
      }
      return configModule.default;
    }
  }
  return null;
};
